### ISSUE TITLE
Pinning large note with plugin enabled is causing obsidian to hang

### ISSUE THREAD

**Issue by joelatschool** [zhaoshenzhai/obsidian-mathlinks#10]
I'm getting a weird issue where certain interactions when a specific large note is open and this plugin is enabled are occasionally causing Obsidian to hang.

I apologize I can't be more specific but I've not been able to narrow down what in particular causes it or find a minimal reproducible example, but I would be willing to send a copy of my vault privately to help diagnose the issue.

Interactions that have caused Obsidian to hang include
- pinning the big note
- closing a lot of tabs simultaneously while the big note is open
- opening the command palette

When this is about to occur, I can sometimes tell because ctrl-hovering over certain links stops popping up a preview box. 

A weird thing that is making the issue harder to diagnose is that even when I have the editor in a state in which pinning a note causes it to hang consistently, if I turn the plugin on and off it stops being in that state and will no longer hang when pinning the note.

**Comment by zhaoshenzhai** [comment]
I'm getting the same issue too, and it seems that just switching between a pinned tab with another tab causes Obsidian to hang (and so does closing a lot of tabs simultaneously).

Whats really bugging me is that, even running Electron (which Obsidian is built on) directly from the command line with logging, I am not getting any errors or crash reports. The issue might take a while to track down, but even if I do, I might not be able to fix it.

**Comment by zhaoshenzhai** [comment]
I'll start by scrapping off functionality from my plugin to pinpoint where the bug is coming from.

**Comment by joelatschool** [comment]
As someone with no electron experience and very little node experience I've tried just messing around with the js debugger in dev tools and what strikes me is that any time you pause you find yourself in the middle of some nodejs infrastructure deep under an editor click handling call, which makes me think that this is some sort of "re-rendering the page is triggering a re-render" situation, or some other variety of async deadlock.  No clue if this is meaningful though.

Also sometimes by messing around with the stepper I've found that I'm occasionally able to get the app unstuck, at which point it will have  double digit numbers of new tabs opened.

**Comment by joelatschool** [comment]
again not sure how much this helps but using git bisect and manual testing, I'm pretty sure that e93b950f87340406ee43b3c7177e34565915f334 is the first  commit with the issue.

**Comment by zhaoshenzhai** [comment]
@joelatschool The issue indeed started from that commit, which added live-preview support. For some reason,

> re-rendering the page is triggering a re-render

for pinned tabs when I checked for a `layout-change`. I will release a fixed version soon.

Thanks for noticing this issue!
