### ISSUE TITLE
MathLink in dataview inline field disappears

### ISSUE THREAD

**Issue by joelatschool** [zhaoshenzhai/obsidian-mathlinks#13]
DataView allows adding a data field to a note inline using the following syntaxes:
```
The game was developed by (developer::[[Mobius Digital]]) and published by [publisher::[[Annapurna Interactive]]].
```
Either of these syntaxes results in new DOM elements being added in reading view in order to add special formatting to these inline fields. This is how it appears in the default theme:
<img width="592" alt="image" src="https://github.com/zhaoshenzhai/obsidian-mathlinks/assets/94202132/ee9d74e0-ae65-466c-a8b3-dbd5f90e2afb">
And this is how it appears in minimal theme:
<img width="592" alt="image" src="https://github.com/zhaoshenzhai/obsidian-mathlinks/assets/94202132/60f840bb-30e0-4382-9f97-a05903f5fdd5">

However, after adding a MathLink to the first link to display an $\aleph$ and to the second to display an $\alpha$, they now appear as follows:
<img width="489" alt="image" src="https://github.com/zhaoshenzhai/obsidian-mathlinks/assets/94202132/7c8dbc22-d286-4775-b997-5cb05c22a737">
<img width="438" alt="image" src="https://github.com/zhaoshenzhai/obsidian-mathlinks/assets/94202132/648737fe-5b87-4220-aeda-5aed65905e7b">

**Comment by zhaoshenzhai** [comment]
Those are the only tests that I ran (never used dataview, so I'm not familiar with any of its other functionality). If there are other cases where links are used in dataview, please let me know and ill include them too. Cheers :)

![Scrot_2023_06_30_152721](https://github.com/zhaoshenzhai/obsidian-mathlinks/assets/47350090/d973b2d7-89df-43d1-ab36-12eb203f4fe5)

**Comment by joelatschool** [comment]
Thanks for the fix! This works for almost everything, although I notice that in the edge case the link is part of a callout and is being rendered in live preview, it still disappears. Should I open a new issue?

**Comment by zhaoshenzhai** [comment]
Could you describe the edge case a bit more? Also, I've completely reworked how mathlinks are handled in live-preview in `0.3.2`, so please update it to this version and see if the issue persists.

**Comment by joelatschool** [comment]
Sure, so if `some definition.md` has a MathLink and you write something like:
```md
>[!theorem]
>(datafield::[[some definition]]) has the universal property that blah blah blah 
```

Then this bug still occurs; in live preview nothing displays for the `some definition.md` link.

**Comment by zhaoshenzhai** [comment]
I see... I'll look into it and see what I can do

**Comment by zhaoshenzhai** [comment]
Though theres still some details to be ironed out, it seems to be working for the most part.
* Top left: source
* Bottom left: reading
* Top right: live-preview hovering outside the callout
* Bottom right: live-preview hovering inside the callout.

Sometimes (can't reliably reproduce yet) the note is still being rendered in live-preview despite switching to source mode, but this seems to only happen with callouts. I'll look into this later when I have some time, but refreshing the note should fix it temporarily.

![Scrot_2023_07_03_133956](https://github.com/zhaoshenzhai/obsidian-mathlinks/assets/47350090/2ee2c3d3-7d40-42cb-aaa1-7b6ea21420f2)
