### ISSUE TITLE
Opening notes in a new tab is broken

### ISSUE THREAD

**Issue by mzietlow** [zhaoshenzhai/obsidian-mathlinks#16]
## Summary

With the latest update, opening notes from a wiki-link with custom text in a new tab is broken.

## Expected Behavior

When holding ctrl while clicking on a wiki-link with custom text, the respective file opens in a **new** tab.

## Current Behavior

When holding ctrl while clicking on a wiki-link with custom text, the respective file opens in the **same** tab.

## Steps to reproduce

- Open a Obsidian Vault.
- Install and enable Mathlinks.
- Create two files 'File A' and 'File B'.
- Inside 'File A', write: 'Hello [[File B|Test B]]'.
- Make sure to move the cursor outside of the wik-link, such that only the text 'Test B' is displayed.
- Hold ctrl while clicking on the wiki-link.

**Comment by zhaoshenzhai** [comment]
Thanks for leaving this issue! It will be fixed in `0.3.3`.
