### ISSUE TITLE
Opening notes in a new tab is broken (mouse-wheel-button)

### ISSUE THREAD

**Issue by mzietlow** [zhaoshenzhai/obsidian-mathlinks#17]
## Summary

Similar to issue #16, opening notes from a wiki-link with custom text in a new tab is broken when using the `mouse-wheel-button` / `mouse-middle-click`.

**Comment by zhaoshenzhai** [comment]
I actually don't have a mouse, so there's no way I can test this right now. However, I've mimicked how I implemented it for the `ctrl` key, so it has a chance of working?

Could you please clone the `mouse-wheel-button` branch and test if it works? After you've cloned the branch, run `npm run dev` and copy `main.js` to your vault. Restart obsidian for the new version to take effect.

Apologies for not being able to test it myself.

**Comment by zhaoshenzhai** [comment]
Also, I'm not familar with how collaborations work on github, so apologies if this is not the right way for you to test my code. If there is a better way, please let me know. It'll be greatly appreciated.

**Comment by zhaoshenzhai** [comment]
I never knew `onauxclick` existed! It fixes my contrived design for checking whether `ctrl` was held down, which was hackily implemented for canvases (they have a sub-document for each node, which made managing `eventListeners` tedious).

I've simplified my implementation by mimicking what you've done above:

```ts
spanOuter.onclick = ((evt: MouseEvent) => {
    evt.preventDefault();
    plugin.app.workspace.openLinkText(this.outLinkFileName, this.outLinkFileName, evt.ctrlKey);
});

spanOuter.onauxclick = ((evt: MouseEvent) => {
    evt.preventDefault();
    if (evt.button == 1) {
        plugin.app.workspace.openLinkText(this.outLinkFileName, this.outLinkFileName, true);
    }
});
```

Based on my tests, the note is opened in a new tab when `ctrl` is held (in canvases as well). It would be appreciated if you could test the same for the mouse.

**Comment by mzietlow** [comment]
I investigated this a little further and found out that I must have had the following lines in my `input.ts`

``` ts
static addMouseMiddleListener(element: HTMLElement) {
        element.addEventListener("mousedown", (evt: MouseEvent) => {
            if (evt.button == 1) {
                evt.preventDefault();
            }
        });
}
```

This is necessary, because otherwise the default action (e.g. autoscroll on windows) is triggered, preventing the auxclick event. For details cf. the [mozilla-docs](https://developer.mozilla.org/en-US/docs/Web/API/Element/auxclick_event#preventing_default_actions) (Section: Preventing default actions)

As a solution to this, I have added another mousedown-listener as follows:

``` ts
            spanOuter.onmousedown = ((evt: MouseEvent) => {
                if (evt.button == 1) {
                    evt.preventDefault();
                }
            });

            spanOuter.onauxclick = ((evt: MouseEvent) => {
                if (evt.button == 1) {
                    plugin.app.workspace.openLinkText(this.outLinkFileName, this.outLinkFileName, true);
                }
            });
```

**Comment by zhaoshenzhai** [comment]
I've implemented your code above. Could you please test it again? Apologies for the back-and-forth.

(I think I messed up branches of this repo, so I merged everything to master.)

**Comment by mzietlow** [comment]
Works on my side 👍
I just noticed another issue, that I think might be worth a second ticket. It goes as follows: 

- Open two notes side by side (a and b). 
- Set focus to note a.
- Try opening a link in note b.
    - It doesn't work, because note b wasn't focused.
- Try opening a link in note b again.
    - It now works, because note b was focused.

Without mathlinks enabled, the focus on note b is not required.

I don't think its too bad of an issue, but still worth pointing out.

**Comment by zhaoshenzhai** [comment]
Nice! Thanks for all your help.

Regarding the focusing issue, I'll probably not have much time to fix it (I'm not a developer of any kind, and only made this plugin out of necessity), so I'll leave it open in a new issue for now.
