### ISSUE TITLE
Command+Click doesn't open links using an alias in new tabs

### ISSUE THREAD

**Issue by joelatschool** [zhaoshenzhai/obsidian-mathlinks#20]
Sorry to keep saddling you with annoying edge case bugs, but I was trying out my sister's MacBook to see if I should switch and I noticed that links that use aliases (i.e. links of the form `[[note|alias]]`) are not opening in a new tab when I Command+Click them. This affects all notes, even those without a MathLink. Even stranger, this starts after enabling MathLinks but seems to persist even after disabling it! It only stops happening for me after restarting Obsidian.

**Comment by zhaoshenzhai** [comment]
The way I handled inputs (even in `0.3.3`) is admitedly really bad, and I am in the process of fixing it. The new solution (currently in the `mouse-wheel-button` branch) should fix these problems.

As for `cmd+click` opening in a new tab, I unfortunately won't be able to test it out. However, [this](https://stackoverflow.com/questions/3902635/how-does-one-capture-a-macs-command-key-via-javascript) stackoverflow post suggests that `event.metaKey` should be able to capture the `cmd` key in Mac, which I've now implemented in the `mouse-wheel-button` branch of this repo. It would be appreciated if you could clone it and test it out.

**Comment by joelatschool** [comment]
Tested it and it seems to work!

**Comment by zhaoshenzhai** [comment]
Nice! I'll merge it after testing some of the other features.
