### ISSUE TITLE
MathLinks conflicts with Supercharged Links in live preview

### ISSUE THREAD

**Issue by joelatschool** [zhaoshenzhai/obsidian-mathlinks#23]
The obsidian addon [Supercharged Links](https://github.com/mdelobelle/obsidian_supercharged_links) allows you to style links to notes based on certain attributes of those notes. For example, in my vault I add the tag `#type/theorem` to any note that represents a theorem, and then use Supercharged Links to add a hook for notes containing that tag. I then use [Style Settings](https://github.com/mgmeyers/obsidian-style-settings) to style links to those notes so that they appear with the character ※ in front of them:
<img width="325" alt="A link to a note called 'example theorem' which appears as '※ example theorem'." src="https://github.com/zhaoshenzhai/obsidian-mathlinks/assets/94202132/60c5c9b8-b9b6-4691-98b6-1ec53e54c690">

When MathLinks is enabled, it prevents Supercharged Links from working in live preview -- any note with a MathLink appears without its Supercharged Links styling.

**Comment by zhaoshenzhai** [comment]
Thanks for leaving this issue! I'll take a look into this when I have some time

**Comment by zhaoshenzhai** [comment]
Apologies for the delay...

I've implemented this feature in the `supercharged-links` branch and it seems to work for my (very limited) tests. Could you please clone that branch and test it out?

There are still some issues though:
* For the supercharged links to appear when the vault is first opened, I need to open its settings page for the links to load properly. But idk if this is a bug in the supercharged-links plugin itself, since it persists even with mathlinks disabled (in a fresh vault too).
* There's probably some edge cases that I haven't handled since I don't personally use the plugin. If you notice anything edge cases, please let me know.

**Comment by joelatschool** [comment]
I couldn't get the test vault to work because the supercharged links plugin wouldn't activate, so instead I tested it by running `npm run dev` and then replacing my copy of main.js from the plugins/mathlinks folder with the version that that built. (Running `npm run build` gives a ton of errors and doesn't build anything). Unfortunately, I don't see any change in the behavior -- in live preview, I still don't see any supercharged links decoration on mathlinks.

**Comment by zhaoshenzhai** [comment]
Hmm, I think this is related to:

> * For the supercharged links to appear when the vault is first opened, I need to open its settings page for the links to load properly. But idk if this is a bug in the supercharged-links plugin itself, since it persists even with mathlinks disabled (in a fresh vault too).

Could you try going to Settings > Community Plugins > Supercharged Links, and see if waiting for about a second activates the plugin?

**Comment by joelatschool** [comment]
I'm not seeing any change; I'm pretty sure the plugin is activated because the decorations show up in Reading View. (Although I have noticed that bug in Supercharged Links where it doesn't activate until you visit the page; it seems to pop up and then resolve itself randomly). 

Is there any way I can confirm I'm running the new version of MathLinks from my vault? If it's working for you then I wonder if the older version is cached or something.

I'll try it next in a debug vault.

**Comment by joelatschool** [comment]
Huh, it's mostly working in the debug vault! (The one issue is that it's still removing decorations that are added to the end of the link). Not sure what's going on in mine then. 😕

**Comment by zhaoshenzhai** [comment]
I'll first fix the decorations at the end of the links. I'm still not sure whether the loading issue is related to mathlinks, as it persists even with mathlinks disabled... I'll make a fresh vault tomorrow and test it further.

**Comment by joelatschool** [comment]
Using the web inspector right now to see if I can get to the bottom of this, I'll let you know if I find anything.

**Comment by joelatschool** [comment]
Ok, I've figured it out! There are two ways to tag a note: inline, like `#type/theorem`, or in the frontmatter, like
```md
---
tags: type/theorem
---
```
.

SL always registers inline tags but only picks up on frontmatter tags when the *Parse all tags in the file* option is set. In the `supercharged-links` branch, ML no longer conflicts with SL for inline tags but still does for frontmatter tags: the `data-link-tags` parameter of the `span` containing the link will be empty. 


I also noticed some other stuff that I'll note here; not sure if it'll be useful but thought I might as well:
- SL adds a decoration before a link by marking some element containing the link with `.data-link-icon` and a bunch of `data-*` parameters, then generating CSS to put some `content` `::before` that element. 
- SL works differently in Reading View vs Live Preview.
- In RV, the link is an `a`, and SL marks it with `.data-link-icon` and gives it the `data-*` parameters.
- In LP, the link is containing in a `span` which SL marks as `.data-link-text` and gives all of the `data-*` parameters. It then seems to add a preceding `span` that it marks as `.data-link-icon` and gives all of the `data-*` parameters to it as well.
- _Except_, a link _with a MathLink_ in LP is both a `span` _and_ gets the `.data-link-icon` class.

**Comment by zhaoshenzhai** [comment]
Fixed this:
> The one issue is that it's still removing decorations that are added to the end of the link

..and this

> SL always registers inline tags but only picks up on frontmatter tags when the _Parse all tags in the file_ option is set. In the `supercharged-links` branch, ML no longer conflicts with SL for inline tags but still does for frontmatter tags: the `data-link-tags` parameter of the `span` containing the link will be empty.

I'm not familiar with the other options tho, but I'll list the ones that I've tested here:
* The inline dataview fields seem to work
* The options of the selectors seem to work too (though, for the background color, only the link has the background color, and not the preppended/appended text)

There are other settings that controls whether SL is enabled in other plugins... Maybe I should open an issue there to give it an option for MathLinks too? Let me know if this is something I should do.

**Comment by zhaoshenzhai** [comment]
> * SL adds a decoration before a link by marking some element containing the link with `.data-link-icon` and a bunch of `data-*` parameters, then generating CSS to put some `content` `::before` that element.
> * SL works differently in Reading View vs Live Preview.
> * In RV, the link is an `a`, and SL marks it with `.data-link-icon` and gives it the `data-*` parameters.

This is essentially what I have done to render the SLs in live-preview (I didn't have to do anything for reading view). My implementation might be really slow though, since it needs to update and re-add an HTML element _every time_ the editor is updated. Let me know if this runs slow for you (I only tested on really small notes...)

**Comment by zhaoshenzhai** [comment]
> * In LP, the link is containing in a `span` which SL marks as `.data-link-text` and gives all of the `data-*` parameters. It then seems to add a preceding `span` that it marks as `.data-link-icon` and gives all of the `data-*` parameters to it as well.
> * _Except_, a link _with a MathLink_ in LP is both a `span` _and_ gets the `.data-link-icon` class.

I didn't want to mess the the preceding `span` that SL creates, since there are usually many spans within a link element and idk what they are for. Again, let me know if this causes an issue.

**Comment by zhaoshenzhai** [comment]
Oh, and one more thing. The 'loading problem' is still an issue in my test vault. Every time I open obsidian, I have to go to...

> Settings > Community Plugins > Supercharged Links

... for SL to enable its decorations (even though the plugin is loaded right away, as seen from the console)

**Comment by zhaoshenzhai** [comment]
Leaving this open for now so I can run more tests...
