### ISSUE TITLE
Some mathlinks doesn't work

### ISSUE THREAD

**Issue by Masacroso** [zhaoshenzhai/obsidian-mathlinks#3]
I have a mathLink that doesn't work. In a note named as `TCdef.sigma álgebra` and with the mathLink in the YAML given by `$\sigma$-álgebra` for some reason it doesn't work. However doing some tests I noticed that if I replace the character `á` in the name of the note by just `a` it works.

**Comment by zhaoshenzhai** [comment]
Hello, thanks for leaving an issue!

It seems to stem from how Obsidian stores `á` as a hexadecimal value, which messes up how the plugin searches for the linked file.

I will look into a permanent solution (other than just `.replace(/%C3%A1/g, 'á')` tomorrow.

**Comment by zhaoshenzhai** [comment]
`0.2.5` should fix the issue! Tell me if theres still something wrong :)

**Comment by Masacroso** [comment]
> `0.2.5` should fix the issue! Tell me if theres still something wrong :)

Now it works! Thank you very much.
