### ISSUE TITLE
Dynamic update is broken in ver. 0.4.2 for reading mode

### ISSUE THREAD

**Issue by RyotaUshio** [zhaoshenzhai/obsidian-mathlinks#35]
Hi, it seems that the dynamic update introduced in ver. 0.4.1 is not working for **reading mode** in ver. 0.4.2. (**live preview seems to be fine**)

I will inspect it when I have time, but it seems like this is caused by the modified implementation of `MathLinksRenderChild.update()`. 

As a quick fix, i tried 
```ts
        if (mathLink) {
            console.log("new mathlink:", mathLink);
            this.containerEl = addMathLink(mathLink, this.containerEl, true);
            // addMathLink(mathLink, this.containerEl, true);
        } else {
            this.containerEl = addMathLink(this.displayText, this.containerEl, true);
            // addMathLink(this.displayText, this.containerEl, true);
        }
```
in the last part of `update()`, and it worked. 
But I feel this might induce another problem... (I'm not sure though)
So keep in mind this is just experimental.

**Comment by zhaoshenzhai** [comment]
Hi! Thanks for pointing it out, it appears I haven't tested it thouroughly Also, I should've consulted this change with you before releasing it; apologies for the headache.

I will address the solutions you proposed in their respective PRs.
