### ISSUE TITLE
Feature Request: Dataview Support

### ISSUE THREAD

**Issue by joelatschool** [zhaoshenzhai/obsidian-mathlinks#4]
This may be a little bit of a difficult request, so feel free to ignore:

Right now, the MathLinks plugin doesn't work on links that are generated by DataView queries. For example, I've set up my notebook so that each page for a math definition has a DataView query that generates a list of links to each page containing a theorem that mentions that definition. Right now, the MathLinks plugin doesn't work on these links.

As a workaround, I've used DataView's query syntax to have the query generate this list by checking each note's metadata for that note's `mathLink` field, and display that text. It then concatenates that with an actual link to that note, set to display as a symbol:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/94202132/213584838-5f521843-52ac-4cdd-9b8b-82f8e2b7a8ad.png">
This kind of works, except for `auto` links.

Is there any way to either have the plugin work on links generated by DataView queries or at least expose `auto`-generated mathLinks for each note within DataView queries (maybe in the metadata or something) so that this workaround could be improved?

**Comment by zhaoshenzhai** [comment]
Ah, the issue is that MathLinks scans the active page for `.internal-links` only, not dataview queries. I've never used dataview, so I never had the need to integrate the two.

I will look into how dataview represents its queries and try to integrate them together... when I have time. If dataview exposes its queries to Obsidian's `MarkdownPostProcessor`, this should be an easy fix.

**Comment by zhaoshenzhai** [comment]
As a side note, it seems that you are in McGill taking MATH457? Its such a coincidence that we're taking the same class haha

**Comment by zhaoshenzhai** [comment]
Hi! Sorry for the late update, but I think I figured it out.

I don't really use dataview, so the example that I cooked up to test my solution might not be exhaustive. Could you please download the latest release and check if it works in your vault?
