### ISSUE TITLE
[Bug] Internal links with extensions are not rendered correctly

### ISSUE THREAD

**Issue by RyotaUshio** [zhaoshenzhai/obsidian-mathlinks#42]
This seems to be a minor issue since most users would prefer links without extensions, but mathLink is not correctly rendered **in reading view** when **a link path has an extension**.

I've noticed the problem is that the condition checks in `setMathLinkGetter` is not going as expected.

https://github.com/zhaoshenzhai/obsidian-mathlinks/blob/32356cd0b4d8005c4aadab7d2a9571f511ce8081/src/links/reading.ts#L46-L59

Probably the following lines have something to do with it. To be honest, I don't fully understand the intention behind them...

- https://github.com/zhaoshenzhai/obsidian-mathlinks/blob/32356cd0b4d8005c4aadab7d2a9571f511ce8081/src/links/reading.ts#L86

- https://github.com/zhaoshenzhai/obsidian-mathlinks/blob/32356cd0b4d8005c4aadab7d2a9571f511ce8081/src/links/reading.ts#L52

Here's some test I've done with v0.4.4 (32356cd0b):

# When both `mathLink` & `mathLink-blocks` are set

## Live preview

<img width="1552" alt="image" src="https://github.com/zhaoshenzhai/obsidian-mathlinks/assets/72342591/c2e2f4a9-c006-4f41-8962-5d9a317c4231">

## Reading view

<img width="1552" alt="image" src="https://github.com/zhaoshenzhai/obsidian-mathlinks/assets/72342591/a8316611-afec-4111-b298-eb2b05965564">

# When `mathLink` is absent

## Live preview

<img width="1552" alt="image" src="https://github.com/zhaoshenzhai/obsidian-mathlinks/assets/72342591/dd9c61d6-5580-4d2a-80e3-e418ec7f7d81">

## Reading view

<img width="1552" alt="image" src="https://github.com/zhaoshenzhai/obsidian-mathlinks/assets/72342591/7f5c5a2c-5373-4933-8961-d32af5b2eed7">

**Comment by zhaoshenzhai** [comment]
Hi, thanks for pointing it out!

> Probably the following lines have something to do with it. To be honest, I don't fully understand the intention behind them...
> 
> * https://github.com/zhaoshenzhai/obsidian-mathlinks/blob/32356cd0b4d8005c4aadab7d2a9571f511ce8081/src/links/reading.ts#L86

The `replace(/\.md/, "")` was added to render links like `[Main](Main.md)` with Main.md having `mathLink: $\alpha$` as $\alpha$ (in MathJax). Without it, it would render as `Main`.

> https://github.com/zhaoshenzhai/obsidian-mathlinks/blob/32356cd0b4d8005c4aadab7d2a9571f511ce8081/src/links/reading.ts#L52

I'm not sure why I specifically picked out the basename either...

I will address your solution in the PR.
