### ISSUE TITLE
Display Issue with Custom Name in Blocklink Enclosed in Escaped Square Brackets When MathLinks is Enabled

### ISSUE THREAD

**Issue by sfsdfc** [zhaoshenzhai/obsidian-mathlinks#46]
I have created a blocklink with a custom display name, and I've enclosed this link in escaped square brackets like this: 
`\[[[#^blocklink|T]]\]`. However, when MathLinks is enabled, the display result seems to have a problem.

Without MathLinks enabled, the display result is: `[T]`

With MathLinks enabled, it appears to add an extra `\[` as shown here: `[\[T]`
![fig](https://github.com/zhaoshenzhai/obsidian-mathlinks/assets/133151823/7890ef0c-fd9a-40e0-b22d-975ed990bd99)

Please refer to the attached image for reference.

**Comment by zhaoshenzhai** [comment]
Hi! Thanks for leaving an issue. I will look into it this weekend.
