### ISSUE TITLE
Render LaTeX in the outliner

### ISSUE THREAD

**Issue by dsaperov** [zhaoshenzhai/obsidian-mathlinks#55]
I think it would be a good idea to make headers containing LaTeX expressions display correctly in the outliner.

I have notes with examples of solving maths problems, and I often put the problems themselves in the headers. Now it looks unreadable in the outliner, and I would be very happy if this plugin could fix this situation.

![image](https://github.com/zhaoshenzhai/obsidian-mathlinks/assets/75473915/8726c6a6-6ff8-4910-931c-73d0f819f280)

**Comment by zhaoshenzhai** [comment]
Hi! Great idea, thanks for pointing it out. I'll take a look into it when I'm free.

**Comment by RyotaUshio** [comment]
I agree this will be very useful, but does it really need to be a part of this plugin? It has nothing to do with links. 
My concern is that adding this feature to this plugin might make this feature difficult for Obsidian users to find and also lead to losing the modularity of plugins.
So I think it should be a independent plugin.

**Comment by dsaperov** [comment]
Hi! It worked great untill the last Obsidian update when they implemented folding/unfolding the outlier items feature. It seems that now LaTeX is not being displayed correctly in the outlier again.
![image](https://github.com/zhaoshenzhai/obsidian-mathlinks/assets/75473915/7ba070c2-a120-4769-9814-f56e809ba932)

**Comment by RyotaUshio** [comment]
@dsaperov  Does [Outline++](https://github.com/RyotaUshio/obsidian-outline-plus) help?

**Comment by dsaperov** [comment]
Great, didn't know about this! Do you have any idea when it will be approved and become available in the community plugin browser?

**Comment by RyotaUshio** [comment]
I have no idea. In general, the Obsidian team doesn't provide any ETA or like, which I think is a reasonable choice.

**Comment by dsaperov** [comment]
I hope they don't take too long with it) Thanks for your work!
