### ISSUE TITLE
Feature Request: Render mathlinks in canvas

### ISSUE THREAD

**Issue by JacobH140** [zhaoshenzhai/obsidian-mathlinks#6]
It would be awesome if mathlinks would render in canvas tiles as well.

**Comment by zhaoshenzhai** [comment]
Hi! I've never tried canvas in my obsidian vault before, so never integrated mathlinks with it. I'll take a look into it this weekend.

**Comment by zhaoshenzhai** [comment]
Hi, apologies for the delay... I got caught up with school work.

It should work now!
