### ISSUE TITLE
Live Preview support

### ISSUE THREAD

**Issue by TheChilliPL** [zhaoshenzhai/obsidian-mathlinks#7]
Math links simply don't work at all in Live Preview mode

**Comment by zhaoshenzhai** [comment]
Thanks for leaving this issue! I've never learnt how editor extensions work in the Obsidian API tbh, so I probably won't be able to fix this anytime soon.

If anyone is able and willing to help, a pr would be most appreciated.

**Comment by zhaoshenzhai** [comment]
Nevermind I figured it out!

Everything should work in `0.2.8`.
